# -*- coding: utf-8 -*-
"""Unemployment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRBVMOYKx2NMXJJz05Zj6Itbuk0ykBiw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("Unemployment in India.csv")

df.head()

df.info()

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

df.shape

df.duplicated().sum()

df.describe()

df.head()

df.columns=['Region','Date','Frequency','Estimated Unemployment Rate','Estimated Employed','Estimated Labour Participation Rate', 'Area']

df.columns

#states with highest unemployment
print("State with highest Unemployment:-",df['Region'].value_counts().idxmax())

print("State with lowest Unemployment:-",df['Region'].value_counts().idxmin())
#states with lowest unemployment

#dropping unwanted columns
df.drop(columns=['Frequency'])

df1=df[['Region','Estimated Unemployment Rate']].groupby('Region').sum().sort_values(by='Estimated Unemployment Rate',ascending=False)

df1.head(10)

fig=plt.figure()
ax0=fig.add_subplot(1,2,1)
df1[:10].plot(kind="bar",color="red",figsize=(20,10),ax=ax0)
ax0.set_title("Top 10 States with Highest Unemployment")
ax0.set_xlabel("State")
ax0.set_ylabel("Number of people unemployed in %")

# Assuming df is your DataFrame
regions = df['Region']
unemployment_rates = df['Estimated Unemployment Rate']

plt.figure(figsize=(10, 6))
plt.bar(regions, unemployment_rates, color='skyblue')
plt.title('Unemployment Rate (State Wise) by Bar Graph')
plt.xlabel('Region')
plt.ylabel('Estimated Unemployment Rate ')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='Region', y='Estimated Unemployment Rate', data=df, palette='Set3')
plt.title('Unemployment Rate (Statewise) by Box Plot')
plt.xlabel('Region')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

regions = df['Region']
unemployment_rates = df['Estimated Unemployment Rate']

plt.figure(figsize=(10, 6))
scatter = plt.scatter(regions, unemployment_rates, c='blue')
plt.title('Unemployment Rate (Statewise) by Scatter Plot')
plt.xlabel('Region')
plt.ylabel('Estimated Unemployment Rate (%)')
plt.xticks(rotation=90)
plt.tight_layout()
plt.colorbar(scatter, label='Region')
plt.show()

plt.figure(figsize=(10, 6))
bars = plt.bar(regions, unemployment_rates, color='skyblue')
plt.title('Unemployment Rate (Statewise) by Histogram')
plt.xlabel('Region')
plt.ylabel('Estimated Unemployment Rate (%)')

plt.xticks(rotation=90)


plt.tight_layout()
plt.show()

"""# **CONCLUSION**

---

1. State with highest Unemployment:- Andhra Pradesh
2. State with Lowest Unemployment:- Chandigarh
3. Graph Progress: Higher The labour participation Lower the unemployment rate
"""